package main

import (
	"io/ioutil"
	"net/http"
	"net/http/httptest" // package to test HTTP handlers
	"testing"
)

func TestPing(t *testing.T) {
	// httptest.ResponseRecorder object can record response status code, headers
	// and body
	// create a new http.ResponseRecorder
	rr := httptest.NewRecorder()
	// Initialize a new dummy http.Request, as a "GET" method and to "/" URL
	r, err := http.NewRequest("GET", "/", nil)
	if err != nil {
		t.Fatal(err) // immediately marks the test as failed and stops the
		// test
	}
	// Call the ping handler function, passing in the
	// httptest.ResponseRecorder and http.Request
	// the http.ResponseWriter of the handler is substituted by the
	// httptest.ResponseRecorder object
	ping(rr, r)
	// Call the Result() method on the http.ResponseRecorder to get the
	// http.Response generated by the ping handler
	rs := rr.Result()
	// check that the status code written by the ping handler was 200.
	if rs.StatusCode != http.StatusOK {
		t.Errorf("expected %d; got %d", http.StatusOK, rs.StatusCode)
	}
	// check that the response body written by the ping handler equals "OK".
	defer rs.Body.Close()
	body, err := ioutil.ReadAll(rs.Body)
	if err != nil {
		t.Fatal(err)
	}
	if string(body) != "OK" {
		t.Errorf("expected body to equal %q", "OK")
	}
}
