package main

import (
	"io/ioutil"
	"log"
	"net/http"
	"net/http/httptest" // package to test HTTP handlers
	"testing"
)

func TestPingUnit(t *testing.T) {
	// httptest.ResponseRecorder object can record response status code, headers
	// and body
	// create a new http.ResponseRecorder
	rr := httptest.NewRecorder()
	// Initialize a new dummy http.Request, as a "GET" method and to "/" URL
	r, err := http.NewRequest("GET", "/", nil)
	if err != nil {
		t.Fatal(err) // immediately marks the test as failed and stops the
		// test
	}
	// Call the ping handler function, passing in the
	// httptest.ResponseRecorder and http.Request
	// the http.ResponseWriter of the handler is substituted by the
	// httptest.ResponseRecorder object
	ping(rr, r)
	// Call the Result() method on the http.ResponseRecorder to get the
	// http.Response generated by the ping handler
	rs := rr.Result()
	// check that the status code written by the ping handler was 200.
	if rs.StatusCode != http.StatusOK {
		t.Errorf("expected %d; got %d", http.StatusOK, rs.StatusCode)
	}
	// check that the response body written by the ping handler equals "OK".
	defer rs.Body.Close()
	body, err := ioutil.ReadAll(rs.Body)
	if err != nil {
		t.Fatal(err)
	}
	if string(body) != "OK" {
		t.Errorf("expected body to equal %q", "OK")
	}
}

// Test end-to-end integration of "/ping" routing, middleare and so on, with
// ping handler
func TestPing(t *testing.T) {
	t.Parallel()
	// Create a new instance of the application struct. For now, this just
	// contains a couple of mock loggers (which discard anything written to
	// them).
	app := &application{
		errorLog: log.New(ioutil.Discard, "", 0),
		infoLog:  log.New(ioutil.Discard, "", 0),
	}
	// use the httptest.NewTLSServer() function to create a new test
	// server, passing in the value returned by the app.routes() method as the
	// handler for the server. This starts up a HTTPS server which listens on a
	// randomly-chosen port of your local machine for the duration of the test.
	ts := httptest.NewTLSServer(app.routes())
	// Shut down the server and block until all outstanding requests of server
	// are done
	defer ts.Close()
	// The network address that the test server is listening on is contained
	// in the ts.URL field. We can use this along with the ts.Client().Get()
	// method to make a GET /ping request against the test server. This
	// returns a http.Response struct containing the response.
	rs, err := ts.Client().Get(ts.URL + "/ping")
	if err != nil {
		t.Fatal(err)
	}
	// We can then check the value of the response status code and body using
	// the same code as before.
	if rs.StatusCode != http.StatusOK {
		t.Errorf("expected %d; got %d", http.StatusOK, rs.StatusCode)
	}
	defer rs.Body.Close()
	body, err := ioutil.ReadAll(rs.Body)
	if err != nil {
		t.Fatal(err)
	}
	if string(body) != "OK" {
		t.Errorf("exptected body to equal %q", "OK")
	}
}

// Test ping handler with functions implemented in testutils
func TestPing2(t *testing.T) {
	// create mock dependencies needed to test server (i.e. loggers)
	app := newTestApplication(t)
	// create a new test server with routing
	ts := newTestServer(t, app.routes())
	defer ts.Close()
	// discard the header being received after test
	statusCode, _, body := ts.get(t, "/ping")
	if statusCode != http.StatusOK {
		t.Errorf("expected %d; got %d", http.StatusOK, statusCode)
	}
	if string(body) != "OK" {
		t.Errorf("expected body to equal %q", "OK")
	}
}
